[
  "test_stage57_calculations.py::Stage57CalculationTests::test_cluster_is_side_specific",
  "test_stage57_calculations.py::Stage57CalculationTests::test_component_sum_matches_score",
  "test_stage57_calculations.py::Stage57CalculationTests::test_consensus_is_side_specific",
  "test_stage57_calculations.py::Stage57CalculationTests::test_duplicates_are_removed",
  "test_stage59_collection_integrity.py::CollectionIntegrityTests::test_fingerprint_changes_when_liquidity_changes",
  "test_stage59_collection_integrity.py::CollectionIntegrityTests::test_fingerprint_is_stable_for_same_rows",
  "test_stage62_btc_directional_alignment.py::Stage62DirectionalAlignmentTests::test_aligned_btc_score_is_continuous",
  "test_stage62_btc_directional_alignment.py::Stage62DirectionalAlignmentTests::test_btc_uses_consensus_only",
  "test_stage62_btc_directional_alignment.py::Stage62DirectionalAlignmentTests::test_market_is_not_part_of_directional_score",
  "test_stage62_btc_directional_alignment.py::Stage62DirectionalAlignmentTests::test_opposite_btc_score_applies_continuous_penalty",
  "test_stage68_tradingview_embed.py::test_bearish_embed",
  "test_stage68_tradingview_embed.py::test_bullish_embed",
  "test_stage68_tradingview_embed.py::test_strong_zone_embed"
]