[
  "test_stage57_calculations.py::Stage57CalculationTests::test_cluster_is_side_specific",
  "test_stage57_calculations.py::Stage57CalculationTests::test_component_sum_matches_score",
  "test_stage57_calculations.py::Stage57CalculationTests::test_consensus_is_side_specific",
  "test_stage57_calculations.py::Stage57CalculationTests::test_duplicates_are_removed",
  "test_stage59_collection_integrity.py::CollectionIntegrityTests::test_fingerprint_changes_when_liquidity_changes",
  "test_stage59_collection_integrity.py::CollectionIntegrityTests::test_fingerprint_is_stable_for_same_rows",
  "test_stage61_price_resolution.py::test_exact_pair_is_preferred",
  "test_stage61_price_resolution.py::test_hype_exchange_info_resolution"
]